[package]
name = "weird_glfw_wgpu_bug"
version = "0.1.0"
authors = ["Friz64 <friz64mc@gmail.com>"]
edition = "2018"

[dependencies]
wgpu = { git = "https://github.com/gfx-rs/wgpu-rs.git", features = ["vulkan"] }
env_logger = "0.6.2"
glfw = "0.32.0"
